id: P007842
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG4006
  title: གཡུ་ཐོག་ཆ་ལག་བཅོ་བརྒྱད་
  author: ''
  volumes:
    901b58e3efe843b5bc55949be99e2ac7:
      image_group_id: I1KG4082
      title: ''
      volume_number: 1
      total_pages: 540
    7f7249d352a54311aa2ca7910b354ac3:
      image_group_id: I1KG4083
      title: ''
      volume_number: 2
      total_pages: 514
ebook_metadata:
  title: གཡུ་ཐོག་ཆ་ལག་བཅོ་བརྒྱད་
  author: ''
  sku: P007842
  cover: cover.jpg
  layers:
  - pagination
