id: P007842
initial_creation_type: ocr
created_at: 21/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W1KG4006
  title: གཡུ་ཐོག་ཆ་ལག་བཅོ་བརྒྱད་
  author: ''
  volumes:
    1db42bac48c84472b9d012e90290a7c5:
      image_group_id: I1KG4082
      title: Volume 1 of g.yu thog cha lag bco brgyad
      volume_number: 1
      total_pages: 540
      base_file: v001.txt
    342eaa6a298e464c841eb37b2883b74c:
      image_group_id: I1KG4083
      title: Volume 2 of g.yu thog cha lag bco brgyad
      volume_number: 2
      total_pages: 514
      base_file: v002.txt
