id: I62884814
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-21T15:03:45+00:00'
last_modified: '2022-06-09T06:28:43.929670+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG4006
  title: གཡུ་ཐོག་ཆ་ལག་བཅོ་བརྒྱད་
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    AABF:
      image_group_id: I1KG4082
      title: Volume 1 of g.yu thog cha lag bco brgyad
      total_pages: 540
      order: 1
      base_file: AABF.txt
    8D81:
      image_group_id: I1KG4083
      title: Volume 2 of g.yu thog cha lag bco brgyad
      total_pages: 514
      order: 2
      base_file: 8D81.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
